[project]
name = "dynamic-modeling"
version = "2026.05.28"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Fabian Roth", email = "roth@cps.tu-darmstadt.de" }
]
requires-python = ">=3.12"
dependencies = [
    "diffrax>=0.7.0",
    "ipywidgets>=8.1.8",
    "klax==0.2.0",
    "matplotlib>=3.10.3",
    "notebook>=6.5.7",
    "tqdm>=4.67.3",
]

[project.scripts]
dynamic-modeling = "dynamic_modeling:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.metadata]
allow-direct-references = true
